CREATE CONSTRAINT IF NOT EXISTS FOR (c:Customer) REQUIRE c.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (p:Product) REQUIRE p.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (o:Order) REQUIRE o.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (cat:Category) REQUIRE cat.id IS UNIQUE;

CREATE INDEX IF NOT EXISTS FOR (p:Product) ON (p.name);
CREATE INDEX IF NOT EXISTS FOR (c:Customer) ON (c.name);
CREATE INDEX IF NOT EXISTS FOR (cat:Category) ON (cat.name);
CREATE INDEX IF NOT EXISTS FOR (p:Product) ON (p.price);